---
- hosts: all
  become: yes
  tasks:

    - name: Find files
      ansible.builtin.find:
        paths: /etc/systemd/system/
        recurse: yes
        file_type: file
        patterns: '*war'
      register: list

    - name: check files
      ansible.builtin.debug:
        var: list